package com.puzzlesolverappbackend.puzzlesolverapp.nonogram.enums;

import java.util.List;

public enum NonogramSolveAction {
    UNKNOWN,
    CORRECT_SEQUENCES_RANGES_IN_ROW, // case LogConverter
    CORRECT_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS_IN_ROW,  // case LogConverter
    CORRECT_SEQUENCES_RANGES_IF_X_ON_WAY_IN_ROW,  // case LogConverter
    CORRECT_SEQUENCES_RANGES_WHEN_MATCHING_FIELDS_TO_SEQUENCES_IN_ROW, //TODO LOG & CONVERTER
    CORRECT_SEQUENCES_RANGES_WHEN_START_FROM_EDGE_INDEX_WILL_CREATE_TOO_LONG_SEQUENCE_IN_ROW,  // case LogConverter
    COLOUR_OVERLAPPING_FIELDS_IN_ROW,  // case LogConverter
    COLOUR_FIELDS_IF_X_WOULD_FORCE_TOO_LONG_COLOURED_FIELDS_SEQUENCE_IN_ROW,  // case LogConverter
    EXTEND_COLOURED_FIELDS_NEAR_X_IN_ROW,  // case LogConverter
    COLOUR_FIELDS_IF_X_CAUSES_ASSIGNMENT_CONFLICT_IN_ROW, //TODO LOG & CONVERTER
    PLACE_XS_AT_UNREACHABLE_FIELDS_IN_ROW,  // case LogConverter
    PLACE_XS_AROUND_LONGEST_SEQUENCES_IN_ROW,  // case LogConverter  // case LogConverter
    PLACE_XS_AT_TOO_SHORT_EMPTY_SEQUENCES_IN_ROW,  // case LogConverter
    PLACE_XS_IF_O_WILL_MERGE_NEAR_FIELDS_TO_TOO_LONG_COLOURED_SEQUENCE_IN_ROW,   // case LogConverter
    PLACE_XS_IF_O_NEAR_X_WILL_BEGIN_TOO_LONG_POSSIBLE_COLOURED_SEQUENCE_IN_ROW, //TODO LOG & CONVERTER
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_IN_ROW, //TODO LOG & CONVERTER
    MARK_AVAILABLE_FIELDS_IN_ROW,  // case LogConverter

    CORRECT_SEQUENCES_RANGES_IN_COLUMN,
    CORRECT_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS_IN_COLUMN,
    CORRECT_SEQUENCES_RANGES_IF_X_ON_WAY_IN_COLUMN,
    CORRECT_SEQUENCES_RANGES_WHEN_MATCHING_FIELDS_TO_SEQUENCES_IN_COLUMN,
    CORRECT_SEQUENCES_RANGES_WHEN_START_FROM_EDGE_INDEX_WILL_CREATE_TOO_LONG_SEQUENCE_IN_COLUMN,
    COLOUR_OVERLAPPING_FIELDS_IN_COLUMN,
    COLOUR_FIELDS_IF_X_WOULD_FORCE_TOO_LONG_COLOURED_FIELDS_SEQUENCE_IN_COLUMN,
    EXTEND_COLOURED_FIELDS_NEAR_X_IN_COLUMN,
    COLOUR_FIELDS_IF_X_CAUSES_ASSIGNMENT_CONFLICT_IN_COLUMN,
    PLACE_XS_AT_UNREACHABLE_FIELDS_IN_COLUMN,
    PLACE_XS_AROUND_LONGEST_SEQUENCES_IN_COLUMN,
    PLACE_XS_AT_TOO_SHORT_EMPTY_SEQUENCES_IN_COLUMN,
    PLACE_XS_IF_O_WILL_MERGE_NEAR_FIELDS_TO_TOO_LONG_COLOURED_SEQUENCE_IN_COLUMN,
    PLACE_XS_IF_O_NEAR_X_WILL_BEGIN_TOO_LONG_POSSIBLE_COLOURED_SEQUENCE_IN_COLUMN,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_IN_COLUMN,
    MARK_AVAILABLE_FIELDS_IN_COLUMN,

    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_COLOURING_PART_IN_ROW,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_PLACE_X_PART_IN_ROW,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_CORRECTING_RANGE_PART_IN_ROW,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_COLOURING_PART_IN_COLUMN,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_PLACE_X_PART_IN_COLUMN,
    PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_CORRECTING_RANGE_PART_IN_COLUMN,

    COLOUR_FIELD_IN_TRIVIAL_ROW,
    COLOUR_FIELD_IN_TRIVIAL_COLUMN,
    PLACING_X_IN_TRIVIAL_ROW,
    PLACING_X_IN_TRIVIAL_COLUMN,

    COLOUR_FIELD_GUESS_OR_RECURSIVE,
    PLACE_X_FIELD_GUESS_OR_RECURSIVE;

    public static List<NonogramSolveAction> getRowSolveActions() {
        return List.of(
                CORRECT_SEQUENCES_RANGES_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS_IN_ROW,
                CORRECT_SEQUENCES_RANGES_IF_X_ON_WAY_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_MATCHING_FIELDS_TO_SEQUENCES_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_START_FROM_EDGE_INDEX_WILL_CREATE_TOO_LONG_SEQUENCE_IN_ROW,
                COLOUR_OVERLAPPING_FIELDS_IN_ROW,
                COLOUR_FIELDS_IF_X_WOULD_FORCE_TOO_LONG_COLOURED_FIELDS_SEQUENCE_IN_ROW,
                EXTEND_COLOURED_FIELDS_NEAR_X_IN_ROW,
                COLOUR_FIELDS_IF_X_CAUSES_ASSIGNMENT_CONFLICT_IN_ROW,
                PLACE_XS_AT_UNREACHABLE_FIELDS_IN_ROW,
                PLACE_XS_AROUND_LONGEST_SEQUENCES_IN_ROW,
                PLACE_XS_AT_TOO_SHORT_EMPTY_SEQUENCES_IN_ROW,
                PLACE_XS_IF_O_WILL_MERGE_NEAR_FIELDS_TO_TOO_LONG_COLOURED_SEQUENCE_IN_ROW,
                PLACE_XS_IF_O_NEAR_X_WILL_BEGIN_TOO_LONG_POSSIBLE_COLOURED_SEQUENCE_IN_ROW,
                PREVENT_EXTENDING_COLOURED_SEQUENCE_TO_EXCESS_LENGTH_IN_ROW,
                MARK_AVAILABLE_FIELDS_IN_ROW);
    }

    public static List<NonogramSolveAction> getCorrectRowRangesSolveActions() {
        return List.of(
                CORRECT_SEQUENCES_RANGES_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS_IN_ROW,
                CORRECT_SEQUENCES_RANGES_IF_X_ON_WAY_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_MATCHING_FIELDS_TO_SEQUENCES_IN_ROW,
                CORRECT_SEQUENCES_RANGES_WHEN_START_FROM_EDGE_INDEX_WILL_CREATE_TOO_LONG_SEQUENCE_IN_ROW);
    }

    public static boolean isMarkRowAction(NonogramSolveAction nonogramSolveAction) {
        return nonogramSolveAction.equals(NonogramSolveAction.MARK_AVAILABLE_FIELDS_IN_ROW);
    }

    public static List<NonogramSolveAction> getColourRowSolveActions() {
        return List.of(COLOUR_OVERLAPPING_FIELDS_IN_ROW, EXTEND_COLOURED_FIELDS_NEAR_X_IN_ROW);
    }

    public static List<NonogramSolveAction> getCorrectColumnRangesSolveActions() {
        return List.of(CORRECT_SEQUENCES_RANGES_IN_COLUMN,
                CORRECT_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS_IN_COLUMN,
                CORRECT_SEQUENCES_RANGES_IF_X_ON_WAY_IN_COLUMN,
                CORRECT_SEQUENCES_RANGES_WHEN_MATCHING_FIELDS_TO_SEQUENCES_IN_COLUMN);
    }

    public static boolean isMarkColumnAction(NonogramSolveAction nonogramSolveAction) {
        return nonogramSolveAction.equals(NonogramSolveAction.MARK_AVAILABLE_FIELDS_IN_COLUMN);
    }

    public static List<NonogramSolveAction> getColourColumnSolveActions() {
        return List.of(COLOUR_OVERLAPPING_FIELDS_IN_COLUMN, EXTEND_COLOURED_FIELDS_NEAR_X_IN_COLUMN);
    }

    public boolean isColumnAction() {
        return name().contains("COLUMN");
    }

    public boolean isRowAction() {
        return name().contains("ROW");
    }
}
