package com.puzzlesolverappbackend.puzzleAppFileManager.nonogram.logic.columnactions.colour.extend.totop;

import org.junit.jupiter.params.provider.Arguments;

import java.util.List;
import java.util.stream.Stream;

public class ExtendColouredFieldsToTopColumnDiff3Test
    extends ExtendColouredFieldsToTopColumnTestBase
    implements ExtendColouredFieldsToTopColumnTestExecutor {

    static Stream<Arguments> provideTestCasesForExtendTop() {
        return Stream.of(
                Arguments.of("o10155.json / 20x15 / diff  / Column 2 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "O", "-", "-", "-", "-"),
                        List.of(List.of(0, 5), List.of(4, 7), List.of(6, 10), List.of(9, 14), List.of(13, 17), List.of(16, 19)),
                        List.of(3, 1, 2, 3, 2, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "X", "O", "-", "-", "-", "-")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "-", "O", "-", "-", "O", "O", "O", "O", "O", "X", "O", "-", "O", "-", "-", "-"),
                        List.of(List.of(0, 7), List.of(6, 12), List.of(14, 19)),
                        List.of(3, 6, 4),
                        List.of("-", "-", "-", "-", "-", "O", "-", "O", "O", "O", "O", "O", "O", "X", "O", "-", "O", "-", "-", "-")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 5 / toTop",
                        List.of("-", "-", "-", "O", "O", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "-", "-", "-"),
                        List.of(List.of(2, 11), List.of(13, 17)),
                        List.of(10, 5),
                        List.of("-", "-", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "-", "-", "-")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "O", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "X", "-"),
                        List.of(List.of(3, 5), List.of(7, 12), List.of(14, 17)),
                        List.of(3, 6, 4),
                        List.of("-", "-", "-", "O", "O", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "X", "-")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 14 / toTop",
                        List.of("-", "-", "O", "-", "-", "X", "-", "O", "-", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X"),
                        List.of(List.of(2, 2), List.of(5, 8), List.of(13, 14)),
                        List.of(1, 3, 2),
                        List.of("-", "-", "O", "-", "-", "X", "O", "O", "-", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 11 / toTop",
                        List.of("-", "-", "O", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "X"),
                        List.of(List.of(1, 3), List.of(8, 8), List.of(10, 16), List.of(18, 18)),
                        List.of(3, 1, 7, 1),
                        List.of("-", "O", "O", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "X")
                ),
                Arguments.of("o10155.json / 20x15 / diff  / Column 2 / toTop",
                        List.of("-", "O", "O", "X", "X", "X", "O", "X", "O", "O", "X", "O", "O", "O", "X", "O", "O", "X", "O", "X"),
                        List.of(List.of(0, 2), List.of(6, 6), List.of(8, 9), List.of(11, 13), List.of(15, 16), List.of(18, 18)),
                        List.of(3, 1, 2, 3, 2, 1),
                        List.of("O", "O", "O", "X", "X", "X", "O", "X", "O", "O", "X", "O", "O", "O", "X", "O", "O", "X", "O", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("-", "-", "-", "-", "O", "O", "-", "-", "-", "-", "-", "O", "O", "-", "-", "O", "-", "X", "O", "-"),
                        List.of(List.of(0, 6), List.of(4, 9), List.of(10, 16), List.of(18, 19)),
                        List.of(3, 2, 6, 2),
                        List.of("-", "-", "-", "-", "O", "O", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "-", "X", "O", "-")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("-", "-", "-", "-", "O", "O", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "X", "X", "O", "O"),
                        List.of(List.of(0, 6), List.of(4, 9), List.of(10, 16), List.of(18, 19)),
                        List.of(3, 2, 6, 2),
                        List.of("-", "-", "-", "-", "O", "O", "-", "-", "-", "-", "O", "O", "O", "O", "O", "O", "X", "X", "O", "O")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 6 / toTop",
                        List.of("X", "X", "-", "-", "O", "O", "X", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X"),
                        List.of(List.of(2, 5), List.of(18, 18)),
                        List.of(4, 1),
                        List.of("X", "X", "O", "O", "O", "O", "X", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 3 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "O", "O", "X"),
                        List.of(List.of(0, 9), List.of(11, 15), List.of(17, 18)),
                        List.of(5, 5, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "X", "O", "O", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 12 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "X", "X"),
                        List.of(List.of(0, 10), List.of(12, 16)),
                        List.of(2, 5),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("X", "-", "-", "-", "O", "-", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(3, 7)),
                        List.of(4),
                        List.of("X", "-", "-", "-", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("-", "-", "O", "X", "O", "O", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "X", "O", "O"),
                        List.of(List.of(0, 2), List.of(4, 5), List.of(10, 15), List.of(18, 19)),
                        List.of(3, 2, 6, 2),
                        List.of("O", "O", "O", "X", "O", "O", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "X", "O", "O")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 9 / toTop",
                        List.of("X", "-", "X", "-", "O", "O", "-", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O"),
                        List.of(List.of(4, 8), List.of(18, 19)),
                        List.of(5, 2),
                        List.of("X", "-", "X", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 11 / toTop",
                        List.of("-", "-", "-", "O", "O", "-", "X", "-", "-", "-", "-", "-", "O", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(3, 4), List.of(8, 12)),
                        List.of(2, 5),
                        List.of("-", "-", "-", "O", "O", "-", "X", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 12 / toTop",
                        List.of("-", "-", "X", "-", "-", "-", "-", "-", "O", "X", "-", "X", "O", "O", "O", "O", "O", "X", "X", "X"),
                        List.of(List.of(7, 9), List.of(12, 16)),
                        List.of(2, 5),
                        List.of("-", "-", "X", "-", "-", "-", "-", "O", "O", "X", "-", "X", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 4 / toTop",
                        List.of("X", "-", "-", "-", "O", "O", "-", "-", "-", "-", "-", "O", "O", "X", "X", "X", "X", "O", "O", "X"),
                        List.of(List.of(4, 5), List.of(8, 12), List.of(17, 18)),
                        List.of(2, 5, 2),
                        List.of("X", "-", "-", "-", "O", "O", "-", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "O", "O", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 1 / toTop",
                        List.of("X", "-", "-", "-", "O", "X", "-", "-", "-", "-", "-", "X", "X", "X", "X", "X", "O", "O", "O", "O"),
                        List.of(List.of(3, 5), List.of(16, 19)),
                        List.of(2, 4),
                        List.of("X", "-", "-", "O", "O", "X", "-", "-", "-", "-", "-", "X", "X", "X", "X", "X", "O", "O", "O", "O")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 3 / toTop",
                        List.of("X", "-", "-", "X", "O", "O", "-", "-", "O", "X", "X", "O", "O", "O", "O", "O", "X", "O", "O", "X"),
                        List.of(List.of(4, 8), List.of(11, 15), List.of(17, 18)),
                        List.of(5, 5, 2),
                        List.of("X", "-", "-", "X", "O", "O", "O", "O", "O", "X", "X", "O", "O", "O", "O", "O", "X", "O", "O", "X")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 19 / toTop",
                        List.of("-", "-", "-", "O", "-", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O"),
                        List.of(List.of(0, 6), List.of(17, 19)),
                        List.of(4, 3),
                        List.of("-", "-", "-", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O")
                ),
                Arguments.of("o07959.json / 20x20 / diff  / Column 18 / toTop",
                        List.of("-", "X", "-", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O"),
                        List.of(List.of(2, 3), List.of(5, 6), List.of(18, 19)),
                        List.of(2, 2, 2),
                        List.of("-", "X", "O", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 17 / toTop",
                        List.of("-", "O", "O", "X", "O", "-", "-", "O", "O", "O", "-", "-", "O", "X", "X", "-", "O", "-", "-", "-"),
                        List.of(List.of(0, 3), List.of(4, 5), List.of(6, 10), List.of(12, 12), List.of(15, 17), List.of(18, 19)),
                        List.of(3, 1, 4, 1, 2, 1),
                        List.of("O", "O", "O", "X", "O", "-", "-", "O", "O", "O", "-", "-", "O", "X", "X", "-", "O", "-", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 1 / toTop",
                        List.of("-", "O", "O", "-", "O", "-", "-", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 5), List.of(6, 14), List.of(9, 19)),
                        List.of(5, 2, 4),
                        List.of("-", "O", "O", "O", "O", "-", "-", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 0 / toTop",
                        List.of("-", "O", "O", "-", "O", "-", "-", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 5), List.of(6, 19)),
                        List.of(5, 2),
                        List.of("-", "O", "O", "O", "O", "-", "-", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 18 / toTop",
                        List.of("X", "-", "O", "O", "O", "O", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "O", "-", "-", "-"),
                        List.of(List.of(1, 6), List.of(9, 19)),
                        List.of(6, 8),
                        List.of("X", "O", "O", "O", "O", "O", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "O", "-", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("-", "O", "X", "X", "O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(4, 5), List.of(8, 19)),
                        List.of(2, 2, 2),
                        List.of("O", "O", "X", "X", "O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 6 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "-", "-", "-", "-", "O", "O", "O", "O", "-", "X", "-", "-"),
                        List.of(List.of(8, 16)),
                        List.of(8),
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "-", "X", "-", "-")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 5 / toTop",
                        List.of("O", "O", "O", "X", "X", "X", "X", "X", "-", "O", "X", "-", "O", "O", "O", "O", "O", "-", "X", "X"),
                        List.of(List.of(0, 2), List.of(8, 9), List.of(11, 17)),
                        List.of(3, 2, 6),
                        List.of("O", "O", "O", "X", "X", "X", "X", "X", "O", "O", "X", "-", "O", "O", "O", "O", "O", "-", "X", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "-", "X", "O", "O", "O", "X", "-", "O", "O", "X"),
                        List.of(List.of(9, 9), List.of(12, 14), List.of(16, 19)),
                        List.of(1, 3, 3),
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "-", "X", "O", "O", "O", "X", "O", "O", "O", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 13 / toTop",
                        List.of("X", "O", "O", "O", "O", "O", "X", "X", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X"),
                        List.of(List.of(1, 5), List.of(10, 15), List.of(17, 18)),
                        List.of(5, 2, 2),
                        List.of("X", "O", "O", "O", "O", "O", "X", "X", "X", "X", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 4 / toTop",
                        List.of("O", "O", "O", "X", "X", "X", "X", "X", "X", "-", "-", "O", "O", "O", "O", "O", "O", "X", "X", "X"),
                        List.of(List.of(0, 2), List.of(9, 16)),
                        List.of(3, 8),
                        List.of("O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 3 / toTop",
                        List.of("X", "O", "O", "X", "O", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X"),
                        List.of(List.of(1, 2), List.of(4, 4), List.of(9, 17)),
                        List.of(2, 1, 9),
                        List.of("X", "O", "O", "X", "O", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "X", "O", "O", "O", "X", "-", "O", "X", "X", "X"),
                        List.of(List.of(5, 5), List.of(9, 9), List.of(11, 13), List.of(15, 16)),
                        List.of(1, 1, 3, 2),
                        List.of("X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "X", "O", "O", "O", "X", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("O", "O", "X", "X", "O", "O", "X", "X", "X", "-", "-", "-", "X", "-", "-", "-", "O", "X", "X", "X"),
                        List.of(List.of(0, 1), List.of(4, 5), List.of(15, 17)),
                        List.of(2, 2, 2),
                        List.of("O", "O", "X", "X", "O", "O", "X", "X", "X", "-", "-", "-", "X", "-", "-", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 15 / toTop",
                        List.of("X", "O", "O", "X", "O", "X", "O", "O", "X", "-", "-", "-", "X", "-", "-", "O", "X", "X", "O", "O"),
                        List.of(List.of(1, 2), List.of(4, 4), List.of(6, 7), List.of(9, 13), List.of(14, 16), List.of(18, 19)),
                        List.of(2, 1, 2, 1, 2, 2),
                        List.of("X", "O", "O", "X", "O", "X", "O", "O", "X", "-", "-", "-", "X", "-", "O", "O", "X", "X", "O", "O")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 14 / toTop",
                        List.of("X", "O", "O", "O", "O", "O", "O", "X", "X", "X", "-", "-", "X", "-", "O", "X", "X", "X", "O", "X"),
                        List.of(List.of(1, 6), List.of(13, 14), List.of(18, 18)),
                        List.of(6, 2, 1),
                        List.of("X", "O", "O", "O", "O", "O", "O", "X", "X", "X", "-", "-", "X", "O", "O", "X", "X", "X", "O", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 13 / toTop",
                        List.of("X", "O", "O", "O", "O", "O", "X", "X", "X", "X", "-", "-", "-", "O", "X", "X", "X", "O", "O", "X"),
                        List.of(List.of(1, 5), List.of(12, 13), List.of(17, 18)),
                        List.of(5, 2, 2),
                        List.of("X", "O", "O", "O", "O", "O", "X", "X", "X", "X", "-", "-", "O", "O", "X", "X", "X", "O", "O", "X")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 16 / toTop",
                        List.of("O", "O", "O", "O", "O", "X", "O", "O", "X", "O", "X", "-", "O", "X", "X", "O", "O", "O", "O", "O"),
                        List.of(List.of(0, 4), List.of(6, 7), List.of(9, 9), List.of(11, 13), List.of(15, 19)),
                        List.of(5, 2, 1, 2, 5),
                        List.of("O", "O", "O", "O", "O", "X", "O", "O", "X", "O", "X", "O", "O", "X", "X", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07940.json / 20x20 / diff  / Column 12 / toTop",
                        List.of("X", "O", "X", "X", "O", "X", "X", "X", "X", "X", "O", "-", "O", "X", "X", "X", "O", "O", "X", "X"),
                        List.of(List.of(1, 1), List.of(4, 4), List.of(10, 12), List.of(16, 17)),
                        List.of(1, 1, 3, 2),
                        List.of("X", "O", "X", "X", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "O", "O", "X", "X")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("-", "-", "O", "-", "O", "-", "O", "X", "-", "-", "O", "-", "-", "-", "-", "-", "-", "O", "X", "-"),
                        List.of(List.of(0, 6), List.of(6, 10), List.of(8, 13), List.of(12, 17), List.of(17, 19)),
                        List.of(5, 1, 2, 3, 1),
                        List.of("-", "-", "O", "O", "O", "-", "O", "X", "-", "-", "O", "-", "-", "-", "-", "-", "-", "O", "X", "-")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("-", "O", "O", "O", "O", "-", "O", "X", "-", "-", "O", "X", "-", "-", "-", "-", "-", "O", "X", "-"),
                        List.of(List.of(0, 5), List.of(6, 6), List.of(9, 10), List.of(12, 17), List.of(17, 19)),
                        List.of(5, 1, 2, 3, 1),
                        List.of("-", "O", "O", "O", "O", "-", "O", "X", "-", "O", "O", "X", "-", "-", "-", "-", "-", "O", "X", "-")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 4 / toTop",
                        List.of("-", "-", "X", "O", "O", "X", "O", "O", "X", "-", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O"),
                        List.of(List.of(0, 4), List.of(3, 7), List.of(6, 10), List.of(9, 13), List.of(12, 16), List.of(18, 19)),
                        List.of(2, 2, 2, 2, 2, 2),
                        List.of("-", "-", "X", "O", "O", "X", "O", "O", "X", "O", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("-", "O", "-", "O", "O", "O", "O", "-", "X", "O", "O", "X", "-", "-", "-", "-", "-", "O", "X", "X"),
                        List.of(List.of(0, 7), List.of(9, 10), List.of(12, 17), List.of(17, 19)),
                        List.of(7, 2, 3, 1),
                        List.of("-", "O", "O", "O", "O", "O", "O", "-", "X", "O", "O", "X", "-", "-", "-", "-", "-", "O", "X", "X")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 1 / toTop",
                        List.of("-", "-", "-", "O", "-", "-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X"),
                        List.of(List.of(0, 10), List.of(4, 12), List.of(6, 15), List.of(16, 18)),
                        List.of(3, 1, 2, 3),
                        List.of("-", "-", "-", "O", "-", "-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "-", "O", "O", "O", "X")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 12 / toTop",
                        List.of("X", "-", "-", "-", "-", "X", "O", "O", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "-", "-"),
                        List.of(List.of(0, 7), List.of(4, 10), List.of(9, 13), List.of(11, 16), List.of(15, 19)),
                        List.of(3, 2, 2, 2, 2),
                        List.of("X", "-", "-", "-", "-", "X", "O", "O", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "-", "-")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 2 / toTop",
                        List.of("X", "-", "O", "O", "O", "X", "-", "X", "O", "O", "-", "-", "-", "-", "X", "O", "O", "X", "O", "O"),
                        List.of(List.of(1, 5), List.of(6, 7), List.of(8, 9), List.of(15, 16), List.of(18, 19)),
                        List.of(4, 1, 2, 2, 2),
                        List.of("X", "O", "O", "O", "O", "X", "-", "X", "O", "O", "-", "-", "-", "-", "X", "O", "O", "X", "O", "O")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 3 / toTop",
                        List.of("O", "-", "O", "O", "O", "X", "O", "O", "X", "O", "O", "X", "-", "-", "X", "O", "X", "O", "X", "O"),
                        List.of(List.of(0, 4), List.of(6, 7), List.of(9, 10), List.of(15, 15), List.of(17, 17), List.of(19, 19)),
                        List.of(5, 2, 2, 1, 1, 1),
                        List.of("O", "O", "O", "O", "O", "X", "O", "O", "X", "O", "O", "X", "-", "-", "X", "O", "X", "O", "X", "O")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 15 / toTop",
                        List.of("X", "X", "X", "-", "-", "O", "O", "-", "-", "X", "O", "-", "O", "X", "-", "X", "O", "O", "O", "X"),
                        List.of(List.of(3, 8), List.of(10, 12), List.of(16, 18)),
                        List.of(4, 3, 3),
                        List.of("X", "X", "X", "-", "-", "O", "O", "-", "-", "X", "O", "O", "O", "X", "-", "X", "O", "O", "O", "X")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 13 / toTop",
                        List.of("X", "X", "X", "X", "X", "-", "O", "X", "-", "-", "O", "-", "X", "-", "X", "O", "X", "O", "X", "O"),
                        List.of(List.of(6, 6), List.of(8, 11), List.of(15, 15), List.of(17, 17), List.of(19, 19)),
                        List.of(1, 3, 1, 1, 1),
                        List.of("X", "X", "X", "X", "X", "-", "O", "X", "-", "O", "O", "-", "X", "-", "X", "O", "X", "O", "X", "O")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 17 / toTop",
                        List.of("X", "X", "X", "X", "O", "X", "X", "-", "-", "X", "O", "O", "O", "O", "-", "O", "X", "O", "X", "X"),
                        List.of(List.of(4, 4), List.of(10, 15), List.of(17, 17)),
                        List.of(1, 6, 1),
                        List.of("X", "X", "X", "X", "O", "X", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "X")
                ),
                Arguments.of("o10357.json / 20x20 / diff  / Column 0 / toTop",
                        List.of("X", "-", "-", "O", "O", "O", "O", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X", "X"),
                        List.of(List.of(3, 8), List.of(17, 17)),
                        List.of(6, 1),
                        List.of("X", "-", "-", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X", "X")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 18 / toTop",
                        List.of("-", "O", "X", "X", "O", "X", "O", "O", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O"),
                        List.of(List.of(0, 2), List.of(4, 4), List.of(6, 9), List.of(14, 14), List.of(18, 19)),
                        List.of(2, 1, 4, 1, 2),
                        List.of("O", "O", "X", "X", "O", "X", "O", "O", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "-", "-", "X", "O"),
                        List.of(List.of(0, 12), List.of(12, 17), List.of(19, 19)),
                        List.of(2, 4, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "-", "-", "X", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 19 / toTop",
                        List.of("-", "-", "O", "O", "O", "O", "O", "X", "-", "-", "O", "O", "O", "O", "O", "O", "O", "O", "-", "-"),
                        List.of(List.of(0, 6), List.of(8, 19)),
                        List.of(7, 10),
                        List.of("O", "O", "O", "O", "O", "O", "O", "X", "-", "-", "O", "O", "O", "O", "O", "O", "O", "O", "-", "-")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 9 / toTop",
                        List.of("-", "-", "X", "-", "-", "-", "-", "-", "X", "-", "-", "-", "-", "O", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(0, 11), List.of(12, 16), List.of(19, 19)),
                        List.of(2, 4, 1),
                        List.of("-", "-", "X", "-", "-", "-", "-", "-", "X", "-", "-", "-", "O", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "X", "-", "-", "-", "O", "X", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(0, 7), List.of(10, 12), List.of(14, 15), List.of(19, 19)),
                        List.of(1, 3, 2, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "X", "-", "O", "O", "O", "X", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("O", "-", "O", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O"),
                        List.of(List.of(0, 5), List.of(15, 15), List.of(19, 19)),
                        List.of(6, 1, 1),
                        List.of("O", "O", "O", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 7 / toTop",
                        List.of("X", "X", "-", "O", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "O", "O", "X", "X", "O"),
                        List.of(List.of(2, 3), List.of(9, 10), List.of(15, 16), List.of(19, 19)),
                        List.of(2, 2, 2, 1),
                        List.of("X", "X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "O", "O", "X", "X", "O")
                ),
                Arguments.of("o07982.json / 20x20 / diff  / Column 0 / toTop",
                        List.of("X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X"),
                        List.of(List.of(5, 17)),
                        List.of(13),
                        List.of("X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X")
                ),
                Arguments.of("o11517.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("-", "-", "-", "O", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 1), List.of(2, 4), List.of(6, 13), List.of(11, 16), List.of(14, 19)),
                        List.of(1, 3, 4, 2, 2),
                        List.of("-", "-", "O", "O", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o11517.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("-", "O", "X", "-", "O", "-", "-", "-", "-", "-", "O", "-", "-", "-", "-", "O", "O", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(3, 6), List.of(7, 13), List.of(12, 19)),
                        List.of(2, 3, 4, 5),
                        List.of("O", "O", "X", "-", "O", "-", "-", "-", "-", "-", "O", "-", "-", "-", "-", "O", "O", "-", "-", "-")
                ),
                Arguments.of("o11517.json / 20x20 / diff  / Column 2 / toTop",
                        List.of("X", "X", "O", "O", "X", "O", "O", "O", "O", "X", "X", "X", "X", "-", "O", "O", "O", "X", "-", "-"),
                        List.of(List.of(2, 3), List.of(5, 8), List.of(13, 16), List.of(18, 19)),
                        List.of(2, 4, 4, 1),
                        List.of("X", "X", "O", "O", "X", "O", "O", "O", "O", "X", "X", "X", "X", "O", "O", "O", "O", "X", "-", "-")
                ),
                Arguments.of("o11517.json / 20x20 / diff  / Column 9 / toTop",
                        List.of("O", "X", "O", "O", "O", "X", "X", "O", "O", "X", "-", "-", "-", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 0), List.of(2, 4), List.of(7, 8), List.of(10, 14), List.of(13, 19)),
                        List.of(1, 3, 2, 2, 3),
                        List.of("O", "X", "O", "O", "O", "X", "X", "O", "O", "X", "-", "-", "O", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 4 / toTop",
                        List.of("-", "O", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "X", "-", "O", "O", "O", "O", "-"),
                        List.of(List.of(0, 2), List.of(9, 11), List.of(14, 19)),
                        List.of(2, 3, 5),
                        List.of("-", "O", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "X", "X", "-", "O", "O", "O", "O", "-")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 12 / toTop",
                        List.of("X", "-", "-", "-", "O", "O", "-", "O", "X", "-", "O", "O", "O", "O", "O", "-", "-", "-", "X", "X"),
                        List.of(List.of(1, 8), List.of(9, 15)),
                        List.of(5, 6),
                        List.of("X", "-", "-", "O", "O", "O", "O", "O", "X", "-", "O", "O", "O", "O", "O", "-", "-", "-", "X", "X")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 2 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "-", "X", "X", "-", "O", "O", "O", "O", "-"),
                        List.of(List.of(0, 7), List.of(8, 11), List.of(14, 19)),
                        List.of(3, 3, 5),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "-", "X", "X", "-", "O", "O", "O", "O", "-")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 10 / toTop",
                        List.of("X", "-", "O", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(1, 3), List.of(8, 10)),
                        List.of(3, 3),
                        List.of("X", "O", "O", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 13 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "X", "X", "X"),
                        List.of(List.of(10, 16)),
                        List.of(7),
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("-", "O", "X", "-", "X", "-", "-", "-", "-", "X", "O", "-", "X", "X", "-", "-", "X", "X", "X", "X"),
                        List.of(List.of(0, 1), List.of(3, 10), List.of(10, 15)),
                        List.of(2, 1, 2),
                        List.of("O", "O", "X", "-", "X", "-", "-", "-", "-", "X", "O", "-", "X", "X", "-", "-", "X", "X", "X", "X")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 1 / toTop",
                        List.of("-", "X", "-", "-", "O", "O", "O", "O", "-", "O", "X", "-", "X", "X", "-", "-", "X", "-", "-", "-"),
                        List.of(List.of(2, 9), List.of(9, 15), List.of(11, 17), List.of(14, 19)),
                        List.of(8, 1, 1, 1),
                        List.of("-", "X", "O", "O", "O", "O", "O", "O", "-", "O", "X", "-", "X", "X", "-", "-", "X", "-", "-", "-")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 6 / toTop",
                        List.of("O", "O", "X", "X", "X", "-", "-", "O", "X", "X", "O", "O", "X", "X", "-", "O", "O", "O", "O", "-"),
                        List.of(List.of(0, 1), List.of(6, 8), List.of(10, 11), List.of(14, 19)),
                        List.of(2, 2, 2, 5),
                        List.of("O", "O", "X", "X", "X", "-", "O", "O", "X", "X", "O", "O", "X", "X", "-", "O", "O", "O", "O", "-")
                ),
                Arguments.of("o07490.json / 20x20 / diff  / Column 2 / toTop",
                        List.of("X", "O", "O", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "-", "O", "O", "O", "O", "X"),
                        List.of(List.of(1, 3), List.of(8, 10), List.of(14, 18)),
                        List.of(3, 3, 5),
                        List.of("X", "O", "O", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "O", "O", "O", "O", "O", "X")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 15 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 12), List.of(4, 16), List.of(9, 19)),
                        List.of(3, 2, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 10), List.of(3, 16), List.of(8, 19)),
                        List.of(2, 2, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 18 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "O", "O", "-", "X", "-", "-", "-", "-", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(0, 8)),
                        List.of(8),
                        List.of("-", "O", "O", "O", "O", "O", "O", "O", "-", "X", "-", "-", "-", "-", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 6 / toTop",
                        List.of("-", "X", "-", "-", "-", "-", "-", "-", "O", "X", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 9), List.of(3, 16), List.of(7, 19)),
                        List.of(2, 2, 2),
                        List.of("-", "X", "-", "-", "-", "-", "-", "O", "O", "X", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 19 / toTop",
                        List.of("-", "-", "X", "O", "-", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(3, 6)),
                        List.of(4),
                        List.of("-", "-", "X", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 8 / toTop",
                        List.of("X", "X", "O", "O", "X", "X", "X", "-", "O", "X", "X", "X", "X", "-", "-", "-", "-", "-", "O", "X"),
                        List.of(List.of(2, 3), List.of(8, 8), List.of(17, 18)),
                        List.of(2, 1, 2),
                        List.of("X", "X", "O", "O", "X", "X", "X", "-", "O", "X", "X", "X", "X", "-", "-", "-", "-", "O", "O", "X")
                ),
                Arguments.of("o07849.json / 20x20 / diff  / Column 6 / toTop",
                        List.of("X", "X", "X", "O", "O", "X", "X", "O", "O", "X", "X", "X", "X", "-", "-", "-", "O", "X", "X", "X"),
                        List.of(List.of(3, 4), List.of(7, 8), List.of(13, 17)),
                        List.of(2, 2, 2),
                        List.of("X", "X", "X", "O", "O", "X", "X", "O", "O", "X", "X", "X", "X", "-", "-", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 1 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "-", "O", "-"),
                        List.of(List.of(0, 11), List.of(3, 13), List.of(12, 19), List.of(27, 29)),
                        List.of(2, 1, 8, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "-", "O", "-")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 7 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "-", "-", "-", "X", "X", "O", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "O"),
                        List.of(List.of(7, 14), List.of(17, 17), List.of(24, 27), List.of(29, 29)),
                        List.of(5, 1, 4, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "-", "-", "-", "X", "X", "O", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 19 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "X", "-", "-", "O", "O", "O", "O", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X"),
                        List.of(List.of(0, 12), List.of(12, 28)),
                        List.of(1, 16),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "X", "-", "O", "O", "O", "O", "O", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 4 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "O", "X", "X", "X", "X", "O", "-", "-", "-", "X", "-", "O", "-", "O", "X", "X", "X", "O"),
                        List.of(List.of(0, 9), List.of(4, 11), List.of(6, 18), List.of(17, 20), List.of(23, 25), List.of(29, 29)),
                        List.of(3, 1, 2, 1, 3, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "O", "X", "X", "X", "X", "O", "-", "-", "-", "X", "-", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 17 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "-", "-", "-", "X", "X", "O", "X", "X", "-", "O", "O", "O", "X", "-", "-", "X", "X", "O"),
                        List.of(List.of(0, 11), List.of(2, 14), List.of(17, 17), List.of(20, 23), List.of(29, 29)),
                        List.of(1, 2, 1, 4, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "-", "-", "-", "X", "X", "O", "X", "X", "O", "O", "O", "O", "X", "-", "-", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "O", "-", "-", "X", "X", "O", "O", "-", "O", "O", "O", "X", "X", "-", "X", "X", "X", "O"),
                        List.of(List.of(0, 13), List.of(4, 18), List.of(17, 25), List.of(29, 29)),
                        List.of(3, 2, 6, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "O", "-", "-", "X", "X", "O", "O", "O", "O", "O", "O", "X", "X", "-", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "-", "-", "X", "X", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "O"),
                        List.of(List.of(0, 11), List.of(3, 14), List.of(17, 17), List.of(22, 24), List.of(29, 29)),
                        List.of(2, 2, 1, 3, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "-", "-", "X", "X", "O", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 18 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "X", "-", "O", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "O", "O"),
                        List.of(List.of(0, 9), List.of(12, 13), List.of(16, 23), List.of(28, 29)),
                        List.of(2, 2, 8, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "X", "O", "O", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 7 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "-", "-", "O", "O", "O", "X", "-", "X", "X", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "X", "O"),
                        List.of(List.of(8, 12), List.of(17, 17), List.of(24, 27), List.of(29, 29)),
                        List.of(5, 1, 4, 1),
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "X", "-", "X", "X", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 14 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "-", "-", "O", "O", "O", "O", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O"),
                        List.of(List.of(9, 13), List.of(17, 17), List.of(26, 29)),
                        List.of(5, 1, 4),
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "-", "O", "O", "O", "O", "O", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 12 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "-", "-", "O", "X", "-", "-", "X", "X", "X", "O"),
                        List.of(List.of(0, 9), List.of(11, 11), List.of(17, 17), List.of(21, 23), List.of(29, 29)),
                        List.of(3, 1, 1, 2, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "-", "O", "O", "X", "-", "-", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 6 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O"),
                        List.of(List.of(7, 9), List.of(11, 12), List.of(17, 17), List.of(27, 29)),
                        List.of(3, 2, 1, 3),
                        List.of("-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 13 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "-", "-", "O", "O", "-", "-", "X", "X", "X", "O"),
                        List.of(List.of(7, 9), List.of(11, 11), List.of(17, 17), List.of(20, 25), List.of(29, 29)),
                        List.of(3, 1, 1, 4, 1),
                        List.of("-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "-", "-", "O", "O", "-", "-", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 12 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "O", "X", "X", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(5, 7), List.of(11, 11), List.of(17, 17), List.of(21, 22), List.of(29, 29)),
                        List.of(3, 1, 1, 2, 1),
                        List.of("-", "-", "-", "-", "-", "O", "O", "O", "X", "X", "X", "O", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 5 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "O", "X", "-", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O"),
                        List.of(List.of(6, 7), List.of(11, 12), List.of(17, 17), List.of(25, 29)),
                        List.of(2, 2, 1, 5),
                        List.of("-", "-", "-", "-", "-", "-", "O", "O", "X", "-", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 10 / toTop",
                        List.of("-", "-", "-", "O", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(0, 5), List.of(7, 9), List.of(11, 14), List.of(17, 19), List.of(29, 29)),
                        List.of(4, 2, 4, 3, 1),
                        List.of("-", "-", "O", "O", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 2 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O"),
                        List.of(List.of(0, 6), List.of(8, 9), List.of(11, 17), List.of(19, 21), List.of(28, 29)),
                        List.of(2, 2, 7, 3, 2),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 4 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(4, 6), List.of(9, 9), List.of(11, 12), List.of(17, 17), List.of(23, 25), List.of(29, 29)),
                        List.of(3, 1, 2, 1, 3, 1),
                        List.of("-", "-", "-", "-", "O", "O", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 11 / toTop",
                        List.of("-", "-", "-", "-", "-", "O", "O", "-", "X", "-", "X", "O", "X", "X", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(3, 7), List.of(7, 9), List.of(11, 11), List.of(14, 14), List.of(17, 17), List.of(19, 20), List.of(29, 29)),
                        List.of(4, 1, 1, 1, 1, 2, 1),
                        List.of("-", "-", "-", "-", "O", "O", "O", "-", "X", "-", "X", "O", "X", "X", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 3 / toTop",
                        List.of("-", "-", "-", "-", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "X", "X", "X", "O", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(3, 4), List.of(9, 9), List.of(11, 13), List.of(17, 17), List.of(21, 23), List.of(29, 29)),
                        List.of(2, 1, 3, 1, 3, 1),
                        List.of("-", "-", "-", "O", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "X", "X", "X", "O", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 10 / toTop",
                        List.of("-", "-", "O", "O", "-", "X", "X", "-", "O", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(0, 4), List.of(7, 9), List.of(11, 14), List.of(17, 19), List.of(29, 29)),
                        List.of(4, 2, 4, 3, 1),
                        List.of("-", "O", "O", "O", "-", "X", "X", "-", "O", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 2 / toTop",
                        List.of("-", "-", "-", "O", "X", "X", "-", "X", "O", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O"),
                        List.of(List.of(0, 3), List.of(8, 9), List.of(11, 17), List.of(19, 21), List.of(28, 29)),
                        List.of(2, 2, 7, 3, 2),
                        List.of("-", "-", "O", "O", "X", "X", "-", "X", "O", "O", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 1 / toTop",
                        List.of("-", "-", "O", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X"),
                        List.of(List.of(1, 2), List.of(8, 8), List.of(12, 19), List.of(27, 28)),
                        List.of(2, 1, 8, 2),
                        List.of("-", "O", "O", "X", "X", "X", "X", "X", "O", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X")
                ),
                Arguments.of("o07804.json / 30x20 / diff  / Column 11 / toTop",
                        List.of("X", "X", "X", "-", "O", "O", "O", "X", "X", "O", "X", "O", "X", "X", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(3, 6), List.of(9, 9), List.of(11, 11), List.of(14, 14), List.of(17, 17), List.of(19, 20), List.of(29, 29)),
                        List.of(4, 1, 1, 1, 1, 2, 1),
                        List.of("X", "X", "X", "O", "O", "O", "O", "X", "X", "O", "X", "O", "X", "X", "O", "X", "X", "O", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O")
                )
        );
    }
}
