package com.puzzlesolverappbackend.puzzleAppFileManager.nonogram.logic.columnactions.colour.extend.totop;

import org.junit.jupiter.params.provider.Arguments;

import java.util.List;
import java.util.stream.Stream;

public class ExtendColouredFieldsToTopColumnDiff2Test
    extends ExtendColouredFieldsToTopColumnTestBase
    implements ExtendColouredFieldsToTopColumnTestExecutor {

    static Stream<Arguments> provideTestCasesForExtendTop() {
        return Stream.of(
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 6 / toTop",
                        List.of("-", "O", "-", "-", "O", "X", "O", "O", "X", "O", "O", "X", "-", "O", "-"),
                        List.of(List.of(0, 2), List.of(3, 4), List.of(6, 7), List.of(9, 10), List.of(12, 14)),
                        List.of(2, 2, 2, 2, 2),
                        List.of("-", "O", "-", "O", "O", "X", "O", "O", "X", "O", "O", "X", "-", "O", "-")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 2 / toTop",
                        List.of("-", "-", "O", "O", "-", "X", "-", "O", "O", "O", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 4), List.of(6, 11), List.of(11, 14)),
                        List.of(4, 5, 2),
                        List.of("-", "O", "O", "O", "-", "X", "-", "O", "O", "O", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 6 / toTop",
                        List.of("O", "O", "X", "O", "O", "X", "O", "O", "X", "O", "O", "X", "-", "O", "X"),
                        List.of(List.of(0, 1), List.of(3, 4), List.of(6, 7), List.of(9, 10), List.of(12, 13)),
                        List.of(2, 2, 2, 2, 2),
                        List.of("O", "O", "X", "O", "O", "X", "O", "O", "X", "O", "O", "X", "O", "O", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 7 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "-", "O", "X", "X"),
                        List.of(List.of(0, 3), List.of(2, 7), List.of(9, 12)),
                        List.of(1, 3, 4),
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 8 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "X", "X", "X", "X"),
                        List.of(List.of(8, 10)),
                        List.of(3),
                        List.of("X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "X", "X", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "-", "O", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(5, 8)),
                        List.of(4),
                        List.of("-", "-", "-", "-", "-", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 7 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "O", "X", "X", "O", "O", "O", "O", "X", "X"),
                        List.of(List.of(0, 3), List.of(4, 6), List.of(9, 12)),
                        List.of(1, 3, 4),
                        List.of("-", "-", "-", "-", "O", "O", "O", "X", "X", "O", "O", "O", "O", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 10 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(3, 6)),
                        List.of(4),
                        List.of("-", "-", "-", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "-", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(0, 5)),
                        List.of(4),
                        List.of("-", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o08007.json / 15x15 / diff 2.0 / Column 5 / toTop",
                        List.of("-", "-", "-", "O", "X", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O"),
                        List.of(List.of(1, 5), List.of(7, 10), List.of(13, 14)),
                        List.of(3, 4, 2),
                        List.of("-", "O", "O", "O", "X", "-", "X", "O", "O", "O", "O", "X", "X", "O", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 17 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "-", "X", "-", "O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 9), List.of(2, 10), List.of(13, 19)),
                        List.of(1, 3, 4),
                        List.of("-", "-", "-", "-", "-", "-", "-", "X", "O", "O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "X", "-", "O", "-", "O", "O", "O", "X", "X", "-"),
                        List.of(List.of(0, 9), List.of(4, 12), List.of(11, 19)),
                        List.of(3, 2, 6),
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "X", "-")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "X", "-", "O", "X", "X", "X", "X", "-", "-", "-"),
                        List.of(List.of(3, 5), List.of(11, 12)),
                        List.of(2, 2),
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "X", "O", "O", "X", "X", "X", "X", "-", "-", "-")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 10 / toTop",
                        List.of("-", "-", "O", "-", "O", "-", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X"),
                        List.of(List.of(0, 5), List.of(10, 16)),
                        List.of(5, 7),
                        List.of("-", "O", "O", "O", "O", "-", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("-", "-", "O", "-", "O", "-", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"),
                        List.of(List.of(0, 5), List.of(10, 19)),
                        List.of(5, 10),
                        List.of("-", "O", "O", "O", "O", "-", "X", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "-", "O", "X", "X", "-", "O", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"),
                        List.of(List.of(1, 3), List.of(5, 7), List.of(9, 19)),
                        List.of(2, 2, 11),
                        List.of("-", "O", "O", "X", "X", "-", "O", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("X", "O", "O", "X", "X", "-", "O", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"),
                        List.of(List.of(1, 2), List.of(5, 6), List.of(9, 19)),
                        List.of(2, 2, 11),
                        List.of("X", "O", "O", "X", "X", "O", "O", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 7 / toTop",
                        List.of("-", "X", "-", "O", "O", "X", "-", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O"),
                        List.of(List.of(2, 4), List.of(6, 9), List.of(11, 19)),
                        List.of(3, 2, 9),
                        List.of("-", "X", "O", "O", "O", "X", "-", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "X", "-", "O", "O", "X", "-", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "X", "X"),
                        List.of(List.of(2, 4), List.of(6, 9), List.of(11, 16)),
                        List.of(3, 2, 6),
                        List.of("-", "X", "O", "O", "O", "X", "-", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "X", "X", "X")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("X", "X", "X", "-", "O", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(3, 4), List.of(11, 12)),
                        List.of(2, 2),
                        List.of("X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("X", "X", "X", "-", "O", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(3, 4), List.of(11, 12), List.of(19, 19)),
                        List.of(2, 2, 1),
                        List.of("X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 4 / toTop",
                        List.of("-", "-", "-", "O", "X", "X", "-", "-", "-", "-", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(2, 4), List.of(12, 13)),
                        List.of(2, 2),
                        List.of("-", "-", "O", "O", "X", "X", "-", "-", "-", "-", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("-", "-", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "O"),
                        List.of(List.of(2, 4), List.of(12, 13), List.of(19, 19)),
                        List.of(2, 2, 1),
                        List.of("-", "-", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "O")
                ),
                Arguments.of("o07942.json / 20x20 / diff 2.0 / Column 3 / toTop",
                        List.of("-", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X"),
                        List.of(List.of(1, 3), List.of(13, 14)),
                        List.of(2, 2),
                        List.of("-", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 16 / toTop",
                        List.of("-", "-", "-", "O", "O", "O", "O", "O", "X", "-", "O", "-", "-", "-", "-", "-", "-", "O", "O", "-"),
                        List.of(List.of(0, 7), List.of(9, 11), List.of(12, 15), List.of(16, 19)),
                        List.of(8, 2, 1, 3),
                        List.of("O", "O", "O", "O", "O", "O", "O", "O", "X", "-", "O", "-", "-", "-", "-", "-", "-", "O", "O", "-")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("-", "-", "-", "-", "-", "O", "-", "O", "-", "X", "O", "-", "-", "-", "-", "-", "-", "-", "X", "O"),
                        List.of(List.of(1, 8), List.of(7, 11), List.of(9, 17), List.of(19, 19)),
                        List.of(5, 2, 2, 1),
                        List.of("-", "-", "-", "-", "O", "O", "-", "O", "-", "X", "O", "-", "-", "-", "-", "-", "-", "-", "X", "O")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("-", "-", "-", "-", "X", "O", "-", "O", "-", "-", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O"),
                        List.of(List.of(0, 6), List.of(3, 8), List.of(5, 10), List.of(12, 16), List.of(18, 19)),
                        List.of(2, 1, 4, 2, 2),
                        List.of("-", "-", "-", "-", "X", "O", "-", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("-", "-", "-", "-", "O", "O", "O", "O", "X", "X", "O", "O", "X", "-", "-", "-", "-", "X", "X", "O"),
                        List.of(List.of(1, 7), List.of(10, 11), List.of(10, 16), List.of(19, 19)),
                        List.of(5, 2, 2, 1),
                        List.of("-", "-", "-", "O", "O", "O", "O", "O", "X", "X", "O", "O", "X", "-", "-", "-", "-", "X", "X", "O")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("-", "-", "-", "O", "X", "O", "X", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O"),
                        List.of(List.of(2, 3), List.of(5, 5), List.of(7, 10), List.of(12, 16), List.of(18, 19)),
                        List.of(2, 1, 4, 2, 2),
                        List.of("-", "-", "O", "O", "X", "O", "X", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-", "X", "O", "O")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("X", "-", "O", "O", "O", "O", "X", "O", "-", "O", "O", "O", "X", "-", "X", "X", "O", "O", "O", "X"),
                        List.of(List.of(1, 5), List.of(7, 11), List.of(16, 18)),
                        List.of(5, 5, 3),
                        List.of("X", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "O", "X", "-", "X", "X", "O", "O", "O", "X")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "O", "X", "O", "X", "X", "-", "-", "-", "X", "X", "O", "X", "-", "-", "-", "-", "X", "X", "-"),
                        List.of(List.of(0, 1), List.of(3, 3), List.of(6, 11), List.of(11, 19)),
                        List.of(2, 1, 1, 1),
                        List.of("O", "O", "X", "O", "X", "X", "-", "-", "-", "X", "X", "O", "X", "-", "-", "-", "-", "X", "X", "-")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("X", "X", "O", "O", "X", "O", "X", "O", "O", "O", "O", "X", "X", "-", "X", "-", "O", "X", "O", "O"),
                        List.of(List.of(2, 3), List.of(5, 5), List.of(7, 10), List.of(15, 16), List.of(18, 19)),
                        List.of(2, 1, 4, 2, 2),
                        List.of("X", "X", "O", "O", "X", "O", "X", "O", "O", "O", "O", "X", "X", "-", "X", "O", "O", "X", "O", "O")
                ),
                Arguments.of("o07929.json / 20x20 / diff 2.0 / Column 15 / toTop",
                        List.of("X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "X", "-", "O", "X", "X", "X", "O", "O"),
                        List.of(List.of(5, 11), List.of(13, 14), List.of(18, 19)),
                        List.of(7, 2, 2),
                        List.of("X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "X", "O", "O", "X", "X", "X", "O", "O")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 2 / toTop",
                        List.of("-", "O", "O", "O", "-", "-", "O", "O", "O", "O", "O", "O", "X", "-", "O", "-", "X", "O", "O", "-"),
                        List.of(List.of(0, 4), List.of(5, 11), List.of(13, 15), List.of(17, 19)),
                        List.of(4, 7, 2, 3),
                        List.of("-", "O", "O", "O", "-", "O", "O", "O", "O", "O", "O", "O", "X", "-", "O", "-", "X", "O", "O", "-")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("-", "O", "O", "O", "X", "X", "-", "-", "O", "O", "O", "-", "-", "X", "O", "O", "O", "O", "O", "O"),
                        List.of(List.of(0, 4), List.of(6, 12), List.of(14, 19)),
                        List.of(4, 5, 6),
                        List.of("O", "O", "O", "O", "X", "X", "-", "-", "O", "O", "O", "-", "-", "X", "O", "O", "O", "O", "O", "O")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 6 / toTop",
                        List.of("X", "O", "-", "X", "X", "X", "-", "-", "-", "O", "-", "-", "-", "O", "O", "O", "-", "X", "X", "O"),
                        List.of(List.of(1, 2), List.of(8, 10), List.of(11, 17), List.of(19, 19)),
                        List.of(2, 2, 5, 1),
                        List.of("X", "O", "-", "X", "X", "X", "-", "-", "-", "O", "-", "-", "O", "O", "O", "O", "-", "X", "X", "O")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 4 / toTop",
                        List.of("O", "X", "X", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "-", "X", "X", "O"),
                        List.of(List.of(0, 0), List.of(3, 3), List.of(5, 13), List.of(13, 16), List.of(19, 19)),
                        List.of(1, 1, 4, 3, 1),
                        List.of("O", "X", "X", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "O", "O", "-", "X", "X", "O")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("X", "-", "-", "X", "X", "X", "-", "-", "-", "O", "-", "O", "-", "X", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(1, 9), List.of(6, 12), List.of(9, 19)),
                        List.of(1, 4, 4),
                        List.of("X", "-", "-", "X", "X", "X", "-", "-", "-", "O", "O", "O", "-", "X", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07834.json / 20x20 / diff 2.0 / Column 6 / toTop",
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "X", "-", "O", "O", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(1, 2), List.of(8, 9), List.of(11, 16), List.of(19, 19)),
                        List.of(2, 2, 5, 1),
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "X", "O", "O", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 6 / toTop",
                        List.of("O", "O", "-", "O", "O", "O", "X", "-", "-", "-", "O", "O", "O", "O", "O", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 5), List.of(7, 17), List.of(16, 19)),
                        List.of(6, 8, 1),
                        List.of("O", "O", "O", "O", "O", "O", "X", "-", "-", "-", "O", "O", "O", "O", "O", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("O", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-", "O", "O", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 4), List.of(6, 9), List.of(9, 15), List.of(15, 17), List.of(17, 19)),
                        List.of(5, 2, 5, 1, 1),
                        List.of("O", "O", "O", "O", "O", "X", "-", "-", "-", "O", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 3 / toTop",
                        List.of("-", "O", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 3), List.of(4, 13), List.of(8, 15), List.of(10, 17), List.of(12, 19)),
                        List.of(3, 3, 1, 1, 1),
                        List.of("O", "O", "O", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 4 / toTop",
                        List.of("-", "O", "O", "O", "X", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 4), List.of(5, 9), List.of(8, 17), List.of(16, 19)),
                        List.of(4, 2, 7, 1),
                        List.of("O", "O", "O", "O", "X", "-", "-", "-", "-", "-", "-", "O", "O", "O", "O", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 2 / toTop",
                        List.of("-", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(3, 16), List.of(8, 19)),
                        List.of(2, 4, 2),
                        List.of("O", "O", "X", "X", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07923.json / 20x20 / diff 2.0 / Column 10 / toTop",
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "-", "O", "X", "-", "O", "-", "-", "-"),
                        List.of(List.of(0, 1), List.of(12, 14), List.of(15, 17), List.of(18, 19)),
                        List.of(2, 2, 2, 1),
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "X", "-", "O", "-", "-", "-")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "-", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "O", "-", "O", "-", "-", "X", "X"),
                        List.of(List.of(0, 7), List.of(5, 17)),
                        List.of(3, 9),
                        List.of("-", "-", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "-", "-", "X", "X")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("O", "O", "X", "X", "X", "-", "X", "-", "O", "O", "O", "-", "-", "X", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 1), List.of(5, 13), List.of(12, 19)),
                        List.of(2, 6, 3),
                        List.of("O", "O", "X", "X", "X", "-", "X", "O", "O", "O", "O", "-", "-", "X", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("X", "O", "X", "X", "X", "-", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "-", "X", "X", "O"),
                        List.of(List.of(1, 1), List.of(5, 7), List.of(11, 16), List.of(19, 19)),
                        List.of(1, 2, 5, 1),
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "-", "X", "X", "O")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "-", "-", "O", "O", "X", "-"),
                        List.of(List.of(1, 2), List.of(8, 12), List.of(14, 19)),
                        List.of(2, 5, 4),
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "X", "-")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "-", "O", "X", "X"),
                        List.of(List.of(0, 1), List.of(8, 12), List.of(16, 17)),
                        List.of(2, 5, 2),
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "O", "O", "X", "X")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "-", "O", "O", "O", "O", "O", "O", "-", "X", "X", "X", "X"),
                        List.of(List.of(7, 15)),
                        List.of(8),
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "-", "X", "X", "X", "X")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X"),
                        List.of(List.of(7, 14)),
                        List.of(8),
                        List.of("X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07702.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "-", "O", "O", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(1, 1), List.of(5, 6), List.of(11, 15), List.of(19, 19)),
                        List.of(1, 2, 5, 1),
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 16 / toTop",
                        List.of("-", "-", "-", "O", "-", "X", "X", "-", "-", "-", "O", "O", "O", "X", "-", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 6), List.of(10, 12), List.of(13, 19)),
                        List.of(4, 3, 2),
                        List.of("-", "O", "O", "O", "-", "X", "X", "-", "-", "-", "O", "O", "O", "X", "-", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "-", "O", "X", "-", "X", "X", "-", "-", "X", "O", "X", "O", "X", "-", "-", "O", "-", "-", "X"),
                        List.of(List.of(0, 2), List.of(4, 10), List.of(10, 12), List.of(12, 14), List.of(14, 18)),
                        List.of(3, 1, 1, 1, 3),
                        List.of("O", "O", "O", "X", "-", "X", "X", "-", "-", "X", "O", "X", "O", "X", "-", "-", "O", "-", "-", "X")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("-", "-", "-", "X", "-", "X", "X", "-", "-", "O", "X", "X", "X", "X", "X", "X", "O", "X", "-", "O"),
                        List.of(List.of(0, 9), List.of(16, 16), List.of(19, 19)),
                        List.of(3, 1, 1),
                        List.of("-", "-", "-", "X", "-", "X", "X", "O", "O", "O", "X", "X", "X", "X", "X", "X", "O", "X", "-", "O")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("X", "-", "O", "X", "X", "X", "X", "-", "-", "X", "O", "O", "O", "X", "X", "X", "X", "O", "X", "X"),
                        List.of(List.of(1, 3), List.of(10, 12), List.of(17, 17)),
                        List.of(2, 3, 1),
                        List.of("X", "O", "O", "X", "X", "X", "X", "-", "-", "X", "O", "O", "O", "X", "X", "X", "X", "O", "X", "X")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("O", "X", "X", "-", "O", "X", "X", "X", "X", "-", "O", "X", "-", "-", "-", "-", "O", "O", "O", "-"),
                        List.of(List.of(0, 0), List.of(3, 5), List.of(10, 10), List.of(15, 19)),
                        List.of(1, 2, 1, 4),
                        List.of("O", "X", "X", "O", "O", "X", "X", "X", "X", "-", "O", "X", "-", "-", "-", "-", "O", "O", "O", "-")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 15 / toTop",
                        List.of("O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "X", "-", "-", "-", "O", "X", "X"),
                        List.of(List.of(0, 0), List.of(2, 3), List.of(8, 8), List.of(10, 12), List.of(15, 17)),
                        List.of(1, 2, 1, 3, 3),
                        List.of("O", "X", "O", "O", "X", "X", "X", "X", "O", "X", "O", "O", "O", "X", "-", "O", "O", "O", "X", "X")
                ),
                Arguments.of("o08436.json / 20x20 / diff 2.0 / Column 16 / toTop",
                        List.of("X", "O", "O", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "-", "O", "X", "X", "X", "X"),
                        List.of(List.of(1, 4), List.of(10, 12), List.of(14, 15)),
                        List.of(4, 3, 2),
                        List.of("X", "O", "O", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "O", "O", "X", "X", "X", "X")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 2 / toTop",
                        List.of("-", "O", "-", "-", "O", "-", "-", "-", "-", "O", "O", "-", "-", "-", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(4, 4), List.of(6, 13), List.of(12, 17), List.of(15, 19)),
                        List.of(2, 1, 6, 2, 1),
                        List.of("-", "O", "-", "-", "O", "-", "-", "-", "O", "O", "O", "-", "-", "-", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 6 / toTop",
                        List.of("-", "O", "-", "-", "O", "-", "-", "-", "-", "-", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(1, 1), List.of(4, 4), List.of(8, 13), List.of(13, 19)),
                        List.of(1, 1, 4, 2),
                        List.of("-", "O", "-", "-", "O", "-", "-", "-", "-", "-", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("-", "O", "-", "-", "O", "-", "O", "-", "-", "O", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(1, 1), List.of(3, 4), List.of(6, 11), List.of(13, 13), List.of(15, 19)),
                        List.of(1, 1, 6, 1, 2),
                        List.of("-", "O", "-", "-", "O", "-", "O", "-", "O", "O", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 17 / toTop",
                        List.of("-", "O", "-", "-", "O", "-", "-", "-", "-", "O", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(4, 4), List.of(6, 13), List.of(15, 19)),
                        List.of(3, 1, 8, 2),
                        List.of("-", "O", "-", "-", "O", "-", "O", "O", "O", "O", "O", "O", "O", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "-", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 4), List.of(2, 13), List.of(10, 16), List.of(13, 19)),
                        List.of(1, 6, 1, 2),
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "O", "O", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "-", "O", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 5), List.of(3, 7), List.of(6, 13), List.of(13, 16), List.of(15, 19)),
                        List.of(2, 1, 6, 1, 2),
                        List.of("-", "-", "-", "-", "O", "-", "-", "-", "O", "O", "O", "O", "-", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 7 / toTop",
                        List.of("-", "O", "X", "-", "O", "X", "X", "X", "X", "X", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(3, 4), List.of(10, 11), List.of(13, 13), List.of(15, 19)),
                        List.of(2, 1, 2, 1, 1),
                        List.of("O", "O", "X", "-", "O", "X", "X", "X", "X", "X", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "O", "X", "-", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 2), List.of(3, 4), List.of(6, 11), List.of(13, 13), List.of(15, 19)),
                        List.of(2, 1, 6, 1, 2),
                        List.of("O", "O", "X", "-", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("X", "O", "X", "-", "O", "O", "O", "X", "X", "O", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(1, 1), List.of(3, 6), List.of(9, 11), List.of(13, 13), List.of(15, 19)),
                        List.of(1, 4, 3, 1, 1),
                        List.of("X", "O", "X", "O", "O", "O", "O", "X", "X", "O", "O", "O", "X", "O", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("O", "O", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "-", "-", "O", "X", "-"),
                        List.of(List.of(0, 1), List.of(4, 4), List.of(6, 11), List.of(13, 13), List.of(16, 17)),
                        List.of(2, 1, 6, 1, 2),
                        List.of("O", "O", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "-", "O", "O", "X", "-")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("X", "X", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "X", "X", "-", "O", "X"),
                        List.of(List.of(4, 4), List.of(6, 11), List.of(13, 13), List.of(17, 18)),
                        List.of(1, 6, 1, 2),
                        List.of("X", "X", "X", "X", "O", "X", "O", "O", "O", "O", "O", "O", "X", "O", "X", "X", "X", "O", "O", "X")
                ),
                Arguments.of("o07924.json / 20x20 / diff 2.0 / Column 10 / toTop",
                        List.of("X", "O", "X", "X", "O", "X", "O", "X", "X", "O", "O", "O", "X", "O", "X", "-", "O", "X", "X", "O"),
                        List.of(List.of(1, 1), List.of(4, 4), List.of(6, 6), List.of(9, 11), List.of(13, 13), List.of(15, 16), List.of(19, 19)),
                        List.of(1, 1, 1, 3, 1, 2, 1),
                        List.of("X", "O", "X", "X", "O", "X", "O", "X", "X", "O", "O", "O", "X", "O", "X", "O", "O", "X", "X", "O")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 11 / toTop",
                        List.of("-", "-", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "O", "-", "O", "-", "-", "X", "X"),
                        List.of(List.of(0, 7), List.of(5, 17)),
                        List.of(3, 9),
                        List.of("-", "-", "-", "-", "X", "-", "-", "-", "X", "O", "O", "O", "O", "O", "O", "O", "-", "-", "X", "X")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("O", "O", "X", "X", "X", "-", "X", "-", "O", "O", "O", "-", "-", "X", "X", "-", "-", "-", "-", "-"),
                        List.of(List.of(0, 1), List.of(5, 13), List.of(12, 19)),
                        List.of(2, 6, 3),
                        List.of("O", "O", "X", "X", "X", "-", "X", "O", "O", "O", "O", "-", "-", "X", "X", "-", "-", "-", "-", "-")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("X", "O", "X", "X", "X", "-", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "-", "X", "X", "O"),
                        List.of(List.of(1, 1), List.of(5, 7), List.of(11, 16), List.of(19, 19)),
                        List.of(1, 2, 5, 1),
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "-", "-", "-", "O", "O", "O", "O", "-", "X", "X", "O")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "-", "-", "O", "O", "X", "-"),
                        List.of(List.of(1, 2), List.of(8, 12), List.of(14, 19)),
                        List.of(2, 5, 4),
                        List.of("X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "O", "O", "O", "O", "X", "-")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "-", "O", "X", "X"),
                        List.of(List.of(0, 1), List.of(8, 12), List.of(16, 17)),
                        List.of(2, 5, 2),
                        List.of("O", "O", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "O", "O", "X", "X")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "-", "O", "O", "O", "O", "O", "O", "-", "X", "X", "X", "X"),
                        List.of(List.of(7, 15)),
                        List.of(8),
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "-", "X", "X", "X", "X")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("X", "X", "X", "X", "X", "X", "X", "-", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X"),
                        List.of(List.of(7, 14)),
                        List.of(8),
                        List.of("X", "X", "X", "X", "X", "X", "X", "O", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07571.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "-", "O", "O", "O", "O", "X", "X", "X", "O"),
                        List.of(List.of(1, 1), List.of(5, 6), List.of(11, 15), List.of(19, 19)),
                        List.of(1, 2, 5, 1),
                        List.of("X", "O", "X", "X", "X", "O", "O", "X", "X", "X", "X", "O", "O", "O", "O", "O", "X", "X", "X", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 1 / toTop",
                        List.of("-", "-", "O", "-", "-", "X", "-", "-", "-", "O", "O", "-", "-", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(0, 4), List.of(6, 13)),
                        List.of(3, 5),
                        List.of("-", "-", "O", "-", "-", "X", "-", "-", "O", "O", "O", "-", "-", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 0 / toTop",
                        List.of("X", "-", "-", "-", "-", "O", "-", "-", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(1, 8)),
                        List.of(5),
                        List.of("X", "-", "-", "-", "O", "O", "-", "-", "-", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 9 / toTop",
                        List.of("-", "-", "-", "-", "-", "-", "O", "O", "-", "X", "-", "X", "-", "-", "-", "-", "X", "O", "O", "O"),
                        List.of(List.of(0, 5), List.of(4, 10), List.of(9, 15), List.of(17, 19)),
                        List.of(3, 4, 2, 3),
                        List.of("-", "-", "-", "-", "-", "O", "O", "O", "-", "X", "-", "X", "-", "-", "-", "-", "X", "O", "O", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("-", "-", "-", "-", "-", "X", "O", "O", "X", "-", "-", "-", "X", "-", "-", "O", "X", "-", "-", "-"),
                        List.of(List.of(0, 7), List.of(3, 15), List.of(9, 19)),
                        List.of(2, 2, 3),
                        List.of("-", "-", "-", "-", "-", "X", "O", "O", "X", "-", "-", "-", "X", "-", "O", "O", "X", "-", "-", "-")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 5 / toTop",
                        List.of("-", "-", "-", "-", "-", "O", "O", "-", "O", "-", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(0, 3), List.of(4, 9), List.of(13, 13)),
                        List.of(1, 5, 1),
                        List.of("-", "-", "-", "-", "-", "O", "O", "O", "O", "-", "X", "X", "X", "O", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 1 / toTop",
                        List.of("-", "-", "O", "-", "O", "X", "-", "-", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(2, 4), List.of(6, 11)),
                        List.of(3, 5),
                        List.of("-", "-", "O", "O", "O", "X", "-", "O", "O", "O", "O", "-", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("-", "-", "-", "-", "X", "O", "O", "X", "-", "-", "-", "O", "-", "O", "-", "X", "O", "O", "O", "O"),
                        List.of(List.of(0, 6), List.of(5, 9), List.of(10, 14), List.of(16, 19)),
                        List.of(2, 2, 4, 4),
                        List.of("-", "-", "-", "-", "X", "O", "O", "X", "-", "-", "-", "O", "O", "O", "-", "X", "O", "O", "O", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 0 / toTop",
                        List.of("X", "-", "-", "-", "O", "O", "-", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(4, 8)),
                        List.of(5),
                        List.of("X", "-", "-", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 8 / toTop",
                        List.of("O", "-", "-", "-", "X", "X", "O", "O", "X", "X", "X", "X", "X", "-", "O", "O", "X", "-", "-", "-"),
                        List.of(List.of(0, 1), List.of(6, 7), List.of(13, 16)),
                        List.of(2, 2, 3),
                        List.of("O", "-", "-", "-", "X", "X", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "X", "-", "-", "-")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 3 / toTop",
                        List.of("X", "O", "O", "X", "X", "O", "O", "X", "X", "X", "X", "-", "O", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(1, 2), List.of(5, 6), List.of(11, 13)),
                        List.of(2, 2, 2),
                        List.of("X", "O", "O", "X", "X", "O", "O", "X", "X", "X", "X", "O", "O", "X", "X", "X", "X", "X", "X", "X")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 12 / toTop",
                        List.of("-", "O", "-", "-", "X", "O", "O", "X", "-", "-", "-", "O", "O", "O", "X", "X", "O", "O", "O", "O"),
                        List.of(List.of(0, 2), List.of(5, 6), List.of(10, 13), List.of(16, 19)),
                        List.of(2, 2, 4, 4),
                        List.of("-", "O", "-", "-", "X", "O", "O", "X", "-", "-", "O", "O", "O", "O", "X", "X", "O", "O", "O", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 13 / toTop",
                        List.of("-", "X", "O", "-", "O", "X", "O", "-", "O", "-", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O"),
                        List.of(List.of(2, 4), List.of(4, 6), List.of(8, 10), List.of(16, 19)),
                        List.of(3, 1, 3, 4),
                        List.of("-", "X", "O", "-", "O", "X", "O", "-", "O", "O", "O", "X", "X", "X", "X", "X", "O", "O", "O", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 14 / toTop",
                        List.of("X", "X", "-", "X", "O", "O", "O", "-", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O"),
                        List.of(List.of(4, 8), List.of(17, 19)),
                        List.of(5, 3),
                        List.of("X", "X", "-", "X", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "O", "O", "O")
                ),
                Arguments.of("o07806.json / 20x20 / diff 2.0 / Column 16 / toTop",
                        List.of("X", "X", "O", "-", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X"),
                        List.of(List.of(2, 8)),
                        List.of(7),
                        List.of("X", "X", "O", "O", "O", "O", "O", "O", "O", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X", "X")
                )
        );
    }
}
