package com.puzzlesolverappbackend.puzzleAppFileManager.puzzlespecific.nonogram;

public enum ActionEnum {
    CORRECT_ROWS_SEQUENCES_RANGES,
    CORRECT_COLUMNS_SEQUENCES_RANGES,
    CORRECT_ROWS_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS,
    CORRECT_COLUMNS_SEQUENCES_RANGES_WHEN_MET_COLOURED_FIELDS,
    CORRECT_ROWS_SEQUENCES_RANGES_IF_X_ON_WAY,
    CORRECT_COLUMNS_SEQUENCES_RANGES_IF_X_ON_WAY,
    COLOUR_OVERLAPPING_FIELDS_IN_ROWS,
    COLOUR_OVERLAPPING_FIELDS_IN_COLUMNS,
    EXTEND_COLOURED_FIELDS_NEAR_X_IN_ROWS,
    EXTEND_COLOURED_FIELDS_NEAR_X_IN_COLUMNS,
    PLACE_XS_ROWS_AT_UNREACHABLE_FIELDS,
    PLACE_XS_COLUMNS_AT_UNREACHABLE_FIELDS,
    PLACE_XS_ROWS_AROUND_LONGEST_SEQUENCES,
    PLACE_XS_COLUMNS_AROUND_LONGEST_SEQUENCES,
    PLACE_XS_ROWS_AT_TOO_SHORT_EMPTY_SEQUENCES,
    PLACE_XS_COLUMNS_AT_TOO_SHORT_EMPTY_SEQUENCES,
    MARK_AVAILABLE_FIELDS_IN_ROWS,
    MARK_AVAILABLE_FIELDS_IN_COLUMNS,
    CORRECT_ROWS_SEQUENCES_RANGES_WHEN_MARKING_FIELDS,
    CORRECT_COLUMNS_SEQUENCES_RANGES_WHEN_MARKING_FIELDS,
}
