#sonar.projectKey=PuzzleSolver
#sonar.projectName=Puzzle Solver Backend
#sonar.host.url=http://localhost:9000
#sonar.login=${env:SONAR_TOKEN}
#sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.token=sqa_415bc11f0c9df4b6ee52c587fdae74a0ceaabbdf